$sources:
  - !pw.io.fs.read
    path: "./data"
    refresh_interval: 30  # seconds

$parser: !pw.xpacks.llm.parsers.ParseUnstructured

$splitter: !pw.stdlib.text.TokenCountSplitter
  chunk_size: 500
  chunk_overlap: 50

$embedder: !pw.xpacks.llm.embedders.OpenAIEmbedder
  model: "text-embedding-3-small"

$knn_index: !pw.stdlib.indexing.BruteForceKnnFactory
  embedder: $embedder
  dimensions: 1536

$bm25_index: !pw.stdlib.indexing.TantivyBM25Factory

$hybrid_index_factory: !pw.stdlib.indexing.HybridIndexFactory
  retriever_factories:
    - $knn_index
    - $bm25_index

$document_store: !pw.xpacks.llm.document_store.DocumentStore
  docs: $sources
  parser: $parser
  splitter: $splitter
  retriever_factory: $hybrid_index_factory

$llm: !pw.xpacks.llm.llms.OpenAIChat
  model: "gpt-4"
  retry_strategy: !pw.udfs.ExponentialBackoffRetryStrategy
    max_retries: 6
  cache_strategy: !pw.udfs.DiskCache
  temperature: 0.05

$server:
  host: "0.0.0.0"
  port: 8000
